### ISSUE TITLE
[Map] Add country statistics to map table

### ISSUE THREAD

**Issue by almosnow** [serratus-bio/open-virome#101]
Country boundaries are loaded into the db.

Compute the intersection of biosample_geographical_location vs. them, same as it is currently being done with Biomes. Add both to the same materialized view on different columns (rationale: samples could belong to a biome AND a country).

**Comment by ababaian** [comment]
Which db? What's this related to?

**Comment by almosnow** [comment]
The `logan` db on AWS RDS.

**Comment by ababaian** [comment]
Merging #102 here
> Once https://github.com/serratus-bio/open-virome/issues/101#issue-2505482380 is ready,
> 
> We can add large geographical regions on top of the country column, this is a simple aggregation of values, ex. North America is a limited list of country codes.
> 
> Aside from this I will add an extra aggregation region for Ocean/Sea to group everything that does not match a land boundary.

**Comment by ababaian** [comment]
From #105 
> We have a table with all the country boundaries and I am trying to generate a materialized view with the list of BioSample and which country boundary do they belong to. We already do this with the biomes so the process would've applied trivially.
> 
> However ... I tried to do this a couple times yesterday and got this back:
>
> (btw, each of these commands take about 5 hours to execute so I cannot just run it each time to see what's going on)
>
> If I run try to build a smaller (100k rows) materialized view, it works. postgres should handle this sort of thing automatically but it's not doing it for whatever reason.
>
> The plan is then to split the creation of the materialized view into as many 100k subqueries as needed, then join them all at the end.



![Image](https://github.com/user-attachments/assets/7ef31106-1cbd-4945-a2d7-f748928040c0)

**Comment by ababaian** [comment]
- Comment in with the solution to solve this problem @almosnow

**Comment by almosnow** [comment]
In summary,

* The "out of memory" error did not go away by increasing memory (we just did like 1 1/2 months ago.
* Creating the materialized view for the biomes dataset (which has a larger number of polygons) does not throw an error, even though it takes twice the time to execute, on average.
* Processing the table in chunks of 1/10th size does not throw an error, but then you'd have to join them at the end and it's not easy to automate/maintain.

Actual solution was:

* Cluster all points based on their lat/lon location rounded to three decimals (~100m distance irl), this greatly reduced the input dataset size (1/40); then resolve the country intersections with this set, no issues; then map them back to their corresponding biosamples.

* The country intersection calculation is much faster (1/40th) but the whole process of mapping them in/out of the reduced resolution space still takes time. Overall it takes about half the time to run everything (~1 hour and a half total).
