### ISSUE TITLE
[Map] Add region boundaries to map table

### ISSUE THREAD

**Issue by almosnow** [serratus-bio/open-virome#102]
Once https://github.com/serratus-bio/open-virome/issues/101#issue-2505482380 is ready,

We can add large geographical regions on top of the country column, this is a simple aggregation of values, ex. North America is a limited list of country codes.

Aside from this I will add an extra aggregation region for `Ocean/Sea` to group everything that does not match a land boundary.

@ababaian if you want other "regions" to be considered, lmk here.

**Comment by ababaian** [comment]
Merging with #101
