### ISSUE TITLE
[UI] GUI Materials for a `National Park` theme for the site

### ISSUE THREAD

**Issue by almosnow** [serratus-bio/open-virome#104]
I just came across this font face and I think it looks quite neat.

Consider using it?

https://nationalparktypeface.com/

**Comment by ababaian** [comment]
I think going with a `National Parks` theme for the whole site would be a real fun direction to take it. This could work yeah.

**Comment by almosnow** [comment]
"Explore the Virome around you 🌲"

**Comment by ababaian** [comment]
Revisit when we go into UI-design
