### ISSUE TITLE
[DB] Country intersections cannot be computed atm.

### ISSUE THREAD

**Issue by almosnow** [serratus-bio/open-virome#105]
We have a table with all the country boundaries and I am trying to generate a materialized view with the list of BioSample and which country boundary do they belong to. We already do this with the biomes so the process would've applied trivially.

However ... I tried to do this a couple times yesterday and got this back:

![Image](https://github.com/user-attachments/assets/6e8b8cbc-66f6-4083-a12e-17ba8e55ed6b)

(btw, each of these commands take about 5 hours to execute so I cannot just run it each time to see what's going on)

If I run try to build a smaller (100k rows) materialized view, it works. postgres should handle this sort of thing automatically but it's not doing it for whatever reason.

The plan is then to split the creation of the materialized view into as many 100k subqueries as needed, then join them all at the end.

**Comment by ababaian** [comment]
This is part of #101, no need to open a seperate issue anytime anything arises, you can document in place of the issue you're addressing.
