### ISSUE TITLE
[Map] Advanced Layout

### ISSUE THREAD

**Issue by almosnow** [serratus-bio/open-virome#107]
Umbrella thread for everything related to the Advanced Map Layout

Current sub-tasks:

- [x] Create an "Ecology (Advanced)" Tab on the UI
- [x] UI Proposal for the Advanced Layout

**Data Aggregation**

- [x] UI Proposal (# of samples, # of biomes, # of countries, # of regions)

**Contig/Sample display**

- [x] https://github.com/serratus-bio/open-virome/issues/53

**Comment by lukepereira** [comment]
Btw, It looks like we'll need to refactor the code a bit to support simple/advanced layout. It doesn't make sense to duplicate simple/advanced in the filters:
<img width="962" alt="Screen Shot 2024-09-11 at 12 33 39 PM" src="https://github.com/user-attachments/assets/8f908bf4-9799-4930-8052-fdc60713a589">


@ababaian I don't think the layout task has enough info yet, it's probably a good idea to clarify what we want throughout the app since there are some UI complications: https://github.com/serratus-bio/open-virome/issues/49. I will leave some comments there.

**Comment by almosnow** [comment]
**UI Proposal for the Advanced Map Layout**

![Image](https://github.com/user-attachments/assets/f52e470e-a8b9-4eb5-beb6-166e22b8ed96)

Each of the proposed modules would live in its own section on the dialogs on the right side of the map.

So far I'm thinking of implementing three (of which a more detailed UI proposal will come next):

* SUMMARY

Meant to give out the most important features of the dataset being shown. In here I plan to put a switch that lets the users toggle between contig/sample view on the map.

* GEOGRAPHICAL FEATURES

Anything that has to do with a parameter that is resolved from geography, the current ones we have are shown. Elevation, temperature, etc... should be in here as well.

* STATISTICS

Anything that comes out of a statistical test performed over the currently represented dataset. Ex. which features are over/under represented. Outliers? Top 10 countries, percentiles, ...

* CONTIGS

Anything related to the contigs associated with a selected point on the map. On "sample" mode it shows you a list of contigs, on "contig" mode it could prob. still show you the same list.

**Comment by lukepereira** [comment]
You may want to check the design on smaller laptop screens. A collapsible component like this might come in handy for displaying multiple dialogs when there's limited space:
https://mui.com/material-ui/react-accordion/#controlled-accordion

I'm also not too convinced we need the simple view, but i think we can figure that out when we review the plan for the other sections

**Comment by almosnow** [comment]
The design will not work on smaller screens.

**Comment by almosnow** [comment]
(unfortunately)

**Comment by ababaian** [comment]
There should be a demarcation between what kind of data is displayed where

![Image](https://github.com/user-attachments/assets/9e44af77-373e-4884-9219-4745792a5e71)

All global `control` or `summary` data for the figure should be near the top, this will propegate look/feel and what kind of data is displayed (e.g. radio buttons for contig/biosample rendering, what to color points by, status message for how many points are displayed)

The pop-up boxes in the map should only contain `Selected Datapoint` data, this is for exactly the point you click on

Summary graphs or aggregation should go below as seperate plots entirely.

Contig summary for example should use the `FASTA` reportingformat from the network graph

![Image](https://github.com/user-attachments/assets/07e94fe1-13ff-48b7-8bf0-205466e9cc8f)

**Comment by ababaian** [comment]
- Move contig example text to Contig issue.
- Due: Wed Sept 19, 2024 --> Meet and discuss map-features with specific issues/timelines written out.

**Comment by almosnow** [comment]
Feature Proposals in a new issue → https://github.com/serratus-bio/open-virome/issues/118
