### ISSUE TITLE
AWS ElastiCache

### ISSUE THREAD

**Issue by almosnow** [serratus-bio/open-virome#112]
We are missing a caching layer that would make the site way more responsive.

https://aws.amazon.com/elasticache/ is a good option, adequate cost, not so hard to set up.

**Comment by lukepereira** [comment]
Some thoughts:

the cache servers involve keeping a high-mem server running, which is a bit counter to the serverless set up. There's also some trade-offs between choosing a large enough cache server to match how similar people's queries will be ( i.e. maxing cache hits vs. misses).

also, I think this task for excluding non-viral data will really speed up the app for most queries and might solve some of the latency problems: https://github.com/serratus-bio/open-virome/issues/78

**Comment by almosnow** [comment]
>the cache servers involve keeping a high-mem server running

No.

But I removed this issue anyway as I changed my mind about doing it. Thought it was removed, lol.
