### ISSUE TITLE
[Map] Render only the most accurate inferred geo data

### ISSUE THREAD

**Issue by almosnow** [serratus-bio/open-virome#117]
Many BioSamples are rendered more than one time on the map.

This is because they have many attributes that allude to some location.

"De-duplicate" (abusing the term a bit) by choosing, and keeping, only the most accurate source of data.

Ex. if the explicit coordinates are already provided, there's no need to render things like "Country Name"

**Comment by almosnow** [comment]
This is up in the frontend and seems to be working well.

However, it must be put into the backend somehow, otherwise Geo queries to things like Biome will still return other points where the extended attribute set matches other things. Example, for the Tundra biome:

![Image](https://github.com/user-attachments/assets/7f54c785-8f49-4104-802e-171df159d2e5)

Easiest way to do this would be to add a boolean column to the geo table (isRepresentative true/false) and then just query that subset; I wouldn't want to remove them completely as they are still needed for other things like the center name queries).

**Comment by ababaian** [comment]
How are you selecting the "Representative" point?

**Comment by almosnow** [comment]
This is the order of preference:

1. Value has explicit coordinates: 23 N 45W or something like that
2. Value comes from a field that mentions **lat**, **lon** or **latlon**.
3. Value inferred from the longest string in all others (assuming longer == more specific).

**Comment by ababaian** [comment]
Beautiful! Stoked to see this thing in a mature state.
