### ISSUE TITLE
[Map] Advanced Layout UI Improvements

### ISSUE THREAD

**Issue by almosnow** [serratus-bio/open-virome#118]
**Over/Under represented features**

- [x] Write Proposal

**Phylogenetics/Taxonomy**

- [ ] Write Proposal

**Institution Location Data**

- [x] Write Proposal

**Comment by almosnow** [comment]
**Over/Under represented features**

We have summary statistics for many features, example w/ Biomes:

![Image](https://github.com/user-attachments/assets/8aa28242-9908-47d1-9b13-d833d5ffbb08)

This is informative but, unfortunately, the "Temperate Broadleaf & Mixed Forests" Biome is over-represented in the whole set. The same thing happens with China if we look at countries.

We could calculate the "background" rate for each of these features, and show it along the summary graph, so the user could know if the distribution being observed is over/under represented for the particular subset.

Visually, I'm picturing something like:

![Image](https://github.com/user-attachments/assets/f6bf8ac7-6c14-4904-a942-adcfb4d3a222)

This applies to all categories/features we currently show to the user.

**Comment by almosnow** [comment]
**Institution Location Data**

In order to make the geographic data more meanginful, we took out the locations related to things like "institution", "research center" and others similar.

Since we have this data already in hand, it would be convenient to show it to the user. This could live in a section titled "SAMPLE METADATA" where we could also show a bit of other properties that we also have already.

It could look like this:

![Image](https://github.com/user-attachments/assets/d7a758ef-35be-4946-b332-fa3380b01469)

**Comment by almosnow** [comment]
**Phylogenetics/Taxonomy**

We also have the taxonomy information and this is quite relevant for anyone exploring a set of viruses (what are they?).

This feature is two small sub-features:
(for some defined rank)

1. Show a summary of the chosen taxonomic rank.

![Image](https://github.com/user-attachments/assets/73dfe5a1-00f7-431c-b4e0-c67dc9addfd0)

2. Color the markers on the map according to broad taxonomic ranks.

**Comment by ababaian** [comment]
Is the issue of statistical interpretation of the distribution of the categories on the radar for this sprint or do we move this to the backlog for Sprint 3?

**Comment by almosnow** [comment]
It should go to Sprint 3, the reason for that is not because it will take long (it won't) it's because we need to discuss a bit what would the background/controls for the statistical test will be.

Something like "vs. all observations under the same virus family" could work, but it could be a different thing (or several, simultaneously).

I'd say let's discuss this next time we do OV meeting, agree on how the test will be performed and then queue it up for implementation.
