### ISSUE TITLE
[LLM] 5 Questions/Queries To Solve

### ISSUE THREAD

**Issue by Stufedpanda** [serratus-bio/open-virome#143]
### Task 2: Define 5 exact questions/queries you would like to solve.
I'd like you to develop 5 "Example User Queries" which solve ask a real biological question, and each one should have a dependency set of different meta-data. In this way you can provide concrete examples of the quality and type of data which is being accessed, and how that addresses the problem. Open a `documentation` issue on the Open Virome repo for this.

For Example: "Show me all datasets in which an arbovirus is found in brain tissue."

The key points here are `Show me all datasets` which is requesting a list of `SRA runs`, does this implicitly entail a summary of their aggregate properties, such as number, technology type, and the meta-data which is available in the `SRA Run Info` tables?

`in which an arbovirus is found` is requesting for a specific class of viruses, namely mosquito-infecting viruses which are Arboviruses. We currently don't have a list of "Arboviruses" anywhere, but this could be generated from the data by intersecting all viruses identified in any dataset belonging to Mosquito taxa. This would be joining `SRA Run Info` table `organism` label, with NCBI taxonomy tables, under the family `Culicidae` (mosquito), then using that list of viruses (Serratus/Logan tables), that would be the "Arbovirus" definition.

`found in brain tissue` this would be a list of SRA runs which have associated tissue metadata matching brain, or a brain-related term such as Neuron, Cerebellum, all of which are stored in the `BRENDA` ontology tables/graph.

At the heart, this question is asking for an intersection of viruses found in at least one dataset where the label is a child member of the `Culcidae` taxonomic family. That list is then intersected with the list of all brain- or brain-associated tissue terms, and those datasets would be reported as the set of "potential Arboviruses".

This is a critically important question because it allows one to ask the related question, "Is this unknown virus which has showed up in this child at Sick Kids, an arbovirus which be linked to the patient's present fever and encephalitis?"

### Outcomes

- `documentation` issue opened on Open Virome repo
- 5 example queries to use for evaluating the model and answering [hypotheses](https://github.com/orgs/serratus-bio/projects/5/views/1?pane=issue&itemId=82993615)
  - Ensure queries have a dependency set of different meta-data
  - Small explanation for each query describing the necessary data to formulate an answer, and the expected output for the model

**Comment by Stufedpanda** [comment]
- "What is Eimeria, and why is it significant to the poultry industry?”
  - Used Bioproject IDs: 15282785
  - Expected Output: Avian Coccidiosis is a disease that inflicts a subclinical infection within poultry, which leads to drastic decreases in the health of poultry and massive losses for the industry. Caused by Eimeria spp., the industry has implemented multiple measures to address the disease, including heavy use of antibiotics. In light of recent studies, Eimeria spp has grown resistant to antibodies and some studies have been conducted to uncover the full extent of symptoms, as well as the mapping of drug-resistant strains of Eimeria tenella to help detect drug-resistance in Eimeria spp in poultry

- "Describe the life cycle of Eimeria and identify the key stages of development."
  - Used Bioproject IDs: 16172343, 17293076, 17008825, 17258541, 17308504
  - Expected Output: Emeria starts out as unsporulated oocysts within the host, and goes through 2 asexual stages of their life, sporozoites and merozoites. They then transition into gametocytes, considered as the sexual stage of the lifecycle, and then into sporulating oocysts, whose spores then proceed to infect new hosts as unsporulated oocysts anew. 
  
- "What are some common clinical signs/symptoms of Eimeria infections?”
  - Used Bioproject IDs: 15282785, 15593932
  - Expected Output: Symptoms include lesions along the gastrointestinal tract leading to a decrease in digestion and absorption in nutrients. 
 
- "How does Eimeria respond to immune systems of its infected hosts?” 
  - Used Bioproject IDs: 12539853, 15593928
  - Expected Output: Response of Eimeria to a host’s immune system seem to be a pre-programmed response derived from the parasite transcriptomes. In particular, a study on mice was conducted, comparing the response of Eimeria across mice with varying levels of immune competence, represented alongside a broad set of gene categories. The variation among mice would force Eimeria to be flexible in order to be successful, however that was not found to be the case, and it was determined that the parasite transcriptomes were no different between mice. Thus it’s concluded that Eimeria has a set response to immune system responses which was proposed as the product of an evolutionary process. 
 
- "How can genomic sequencing contribute to understanding the virulence factors of Eimeria, and what implications does this have for treatment strategies?"
  - Used Bioproject IDs: 12539853, 15593928 (same as above query)
  - Expected Output: Genomic sequencing could reveal patterns in virulence factors that define Eimeria. As per the same study found in query 4, it seems that the virus is not flexible in its adaptability to hosts and uses a preset response to any sort of level of immune response. Understanding the factors and patterns that dictate Eimeria’s virulence through its genome sequence could lead to significant advancements in treating symptoms as we learn more about what the symptoms are and what causes them at a genomic level.

**Comment by lukepereira** [comment]
For future reference, you should share the id under the attribute `bioProject` instead, e.g. 15282785 - PRJNA623634. the one you shared is an internal node id used by neo4j

**Comment by lukepereira** [comment]
[still reviewing]

I came up with some building blocks which should capture some distinctions between types of queries. we'll want to narrow down what to focus on and how to evaluate:

- Virome vs. text queries:
    - virome: answer returns a set of runs or a "virome"  
    - text: answer returns a text response
- Local vs. Global:
    - local: answer involves a single community/virome
    - global: answer involves comparison between all communities
- Retrieval vs. Interpretation:
    - retrieval: answer is direct retrieval of info from database
    - interpretation: answer is derived from available data
- In- vs. out-of distribution
    - in-distribution: answer is directly within database
    - out-of-distribution: answer is not in database but entirely from LLM 

Related to retrieval: we can also explore using the LLM to generate queries in a query language (Neo4j cypher or GraphQL). This would support generating more complex queries since the RAG approach is embedding based and will be less precise.

Related to interpretation: we should consider capabilities in the recent [o1 chain-of-thought](https://openai.com/index/learning-to-reason-with-llms#chain-of-thought), where the LLM can formulate and perform different numerical and reasoning tests and comparisons before coming to a conclusion.

**Comment by lukepereira** [comment]
https://github.com/serratus-bio/open-virome-llm/blob/main/eval_files/query.topics
