### ISSUE TITLE
Allow users to query by list of SRA identifiers (RunId, BioSample, BioProject)

### ISSUE THREAD

**Issue by lukepereira** [serratus-bio/open-virome#145]
### What would you like to be added?

In filters, include an 'SRA Identifiers' field which shows text boxes for Run id, BioSample, Bioproject.

Only include identifiers that are present in our DB and display counts of matches.

In filter tag on header, show "SRA Ids: Custom".

QA:
- Check behaviour when mixing virus positive and negative queries and identifiers
- Check behaviour when mixing custom id query with filters

### Why is this needed?

This feature makes it easier to query for specific SRA ids and makes it easier to integrate results from other tools, like kmindex.

### Additional context

A future task can allow setting app state directly from URL, either with url params or using session ids. Using URL params may not be able to handle a large number of IDs.

**Comment by lukepereira** [comment]
I pushed an initial version with the core functionality, I ran into some complications when handling functionality that doesn't match the existing filter behaviour:

- Querying by direct input ids should include runs with no viruses
- Querying by direct input ids should have OR behaviour with other filters instead of AND

LMK if we want to make these changes and whether I should prioritize them (likely for next week), otherwise they can be added to the backlog as future improvements

**Comment by ababaian** [comment]
Two birds with one stone. We can solve this problem and a great functionality.

We should distinguish `Manual-Entry Virome` and `Query-Builder Virome`

### `Manual-Entry Virome` 
User can input exact lists of SRA Run Accessions to make the `Target Set` and `Control Set`. This is independent of other filters. Until there are `NOT` operators, I think the only solution will be to keep these as exclusive functions.


### `Query Builder Virome` 
As currently it is. To bridge the functionality of Query Builder with Manual Entry (and add persistence). Add an `Export Run Lists` button to save SRA Runs in the current `Target Set` and `Control Set`. The benefit here is that once a list of Runs is generated, that in essence saves the "Session State" of the query builder to what is displayed and adds persistence between sessions.

With this in mind, I would say make the direct input ID all belong to `Target Set`, with no "BioProject" control function, and no "Virus Negative" control functionality. And exclude mixing of Query Builder filters with a direct input list (until more mature query building can be implemented DSI hopefully)

**Comment by lukepereira** [comment]
This makes sense. The implementation issues would be resolved by storing them in different state and preventing mixing. 

Also, having a distinction between the different ways to query will set us up to support other cases in the future, like palmid, kmer, free text LLM, Graphql Query language, etc.

I have a pretty good idea on what the UI/UX should be, but let me know if you have something specific in mind.

**Comment by lukepereira** [comment]
Another feature to solve the first point fairly easily would be to have a global setting to toggle whether to make queries return virus only or include non-virus runs. Though there will still speed issues and it might be reasonable for the app to focus on virus data.

**Comment by ababaian** [comment]
I think the toggle makes sense

For a list of "Eimeira" datasets, only 1,000/3,000 input are found 
![Image](https://github.com/user-attachments/assets/e5e2c7b4-6ace-435d-88c6-57a9707d42cf)

But once a set is loaded, a really nice feature is to sub-set them based on sub-sequent filters. So I can see the benefit of a hybrid too, but implementing the hybrid well is tricky, but something that we should revisit.

![Image](https://github.com/user-attachments/assets/884b5262-e048-4f7c-942b-9eb02eb69558)
