### ISSUE TITLE
[Feature] Update Geographic Datapoint selection

### ISSUE THREAD

**Issue by ababaian** [serratus-bio/open-virome#37]
![image](https://github.com/serratus-bio/open-virome/assets/9220907/2ca756eb-659e-4b78-8222-fea84001186f)

**Comment by almosnow** [comment]
Still missing the sOTU values, but some steps in that direction → https://github.com/serratus-bio/open-virome/commit/d6bf309e687f647ff90e24ee13a3f7da261eafd8

**Comment by ababaian** [comment]
So key detail here, how many `bioSamples` had runs retrieved within them? On `palmID` this was reported as `geo-data for 488 / 621 runs retrieved`
![image](https://github.com/user-attachments/assets/a28311d0-a3f1-4459-8cc1-3423c18351fd)


Can you add this text Above the plot please?

Also right now there are `133` points in the table, but nothing is rendering online:

![image](https://github.com/user-attachments/assets/093254f2-c97d-4140-ba5a-666762161ae9)
![image](https://github.com/user-attachments/assets/42bc2026-ee0f-4a26-8a51-d7d18da9dcd4)

**Comment by almosnow** [comment]
Oka, let me check why those are not showing

**Comment by almosnow** [comment]
I think this is also because of https://github.com/serratus-bio/open-virome/issues/42

**Comment by lukepereira** [comment]
noticed a bug where the map doesn't get refreshed after adding/removing filters. can take a look next week

**Comment by ababaian** [comment]
Update: related to this, if more than `limit` data points are selected and only the `limit` amount are shown, this shoud be explicitly returned as a status message.

**Comment by ababaian** [comment]
Please add a `Time Estimate:` for this issue.

**Comment by almosnow** [comment]
This one's (at least) three bundled issues:

* Text with aggregation statistics
* Change popup behavior from hovering to clicking
* Show a status message when the max number of retrieved points has been reached

Also:

* Put all this information inside a window hovering around inside the map (@ababaian you want this Y/N?)

Time Estimate: 3 hours each

**Comment by almosnow** [comment]
Progress:

* Changed the behavior from hover to click
* Made the circle hit test slightly larger so they're easier to 'pick'
* Added a small window _inside_ the map and re-arranged the data there

* Tried to find a way to highlight picked points but no luck so far

**Comment by ababaian** [comment]
- Click behaviour and window inside is easier for sure, nice

Don't worry about highlighting this is feature creep, the key objective is being able to provide summary messages about the entire retrieval, this can be displayed as seperate text below the figure, does not have to be a pop-up. You'll want to show messages like

`Geographic points found for 750/1000 (75%) bioSamples, and 1500/5000 (30%) of contigs.`

`Max point limit (50,000 points) reached. Not all points rendered.`
