### ISSUE TITLE
[Feature] Implement `Simple` and `Advanced` views for each module

### ISSUE THREAD

**Issue by ababaian** [serratus-bio/open-virome#49]
Currently within each module, different figures are shown as pull-down menu

![image](https://github.com/user-attachments/assets/3b60940c-e108-4175-a75d-6cb3486dc665)

click

![image](https://github.com/user-attachments/assets/172d3df0-35c2-451f-8ba1-526cd8c333f2)

Change this to "tabs" for each graph type so users can immediatly see that more data is available. It's not clear that this is a click-able entry, and what other information is present. If we use a gray color for non-selected tabs it will keep the visual distractions of non-selected items down.

**Comment by lukepereira** [comment]
We can try this out. I still think it will add a lot of text, i.e. for the metadata module it would have: Geography, Host (STAT), Tissue, Sex, and we'll likely continue adding more.

probably a good strategy is to open issues for the problem with the app and then we can collectively propose/discuss potential solutions in the comments

**Comment by ababaian** [comment]
Certainly re: discussion.

In terms of representation, I think we're going to have to go over it a few times as the application matures so nothing will be set in stone, but we can work through it with incremental improvements.

I'm actually of the mind that all the graphs should be shown without having to click through anything for a given module. Like so...

![image](https://github.com/user-attachments/assets/5d2a97fa-97df-480b-82e5-d0da2f168f0f)

![image](https://github.com/user-attachments/assets/d6b40d84-6775-4215-ba70-6e883cad7533)

https://serratus.io/palmid?hash=3xample

The added benefit is that the more complex renders such as the network module does not have to be shown/calculated until the user clicks over to that tab.

**Comment by lukepereira** [comment]
the full page render is also do-able with lazy-loading, so it only fetches and renders a figure when it enters the viewport. 

the iterative approach is fine for now and if we land a good designer they'll can hopefully give us the best solution directly

**Comment by ababaian** [comment]
Email sent, we'll see how this goes but it's the first step in opening a work order regardless

**Comment by lukepereira** [comment]
> Shoichi Sakaguchi
> The network viewer in “Virus Species / Virus Family / sOTU” should be bigger.

Another layout option to consider would be to keep the existing landing page of three modules and include an "expand" icon in each module that opens all of its figures in a wide view. 

IMO this could be better than the tabs because users can look at three modules on the base page which is more visual appealing

**Comment by ababaian** [comment]
I think to be fair this is bikeshedding, let's get the functionality together then we can see how best to tweak it, but a "Maximize View" I agree is the right compromise to do this quickly

**Comment by ababaian** [comment]
I think the solution to this UI problem is not to have one plot type per view, but to make the views in the pull-down menu
- `Simple`: top-level stuff, "Just show me the summary"
- `Advanced` detailed view, "Show me all the good stuff!"

This pretty much will cover the two major user-types

**Comment by lukepereira** [comment]
It's not clear if we want simple/advanced views per table, i.e.
- Ecology (Simple), Ecology (Advanced)
- Tissue (Simple), Tissue (Advanced)

or simple/advanced views for each section, i.e.
- Run (Simple), Run (Advanced)
- Metadata (Simple), Metadata (Advanced)


We should consider if multiple sections can display advanced views and how the page will handle rendering a large number of plots.

Also, would be useful to roughly know what the Simple/Advanced layouts should look like for different sections, I'm not too sure what the virome behaviour would be.

**Comment by ababaian** [comment]
- Implement for `SRA Run Info` and nominally for `Virome` modules.
