### ISSUE TITLE
Improve onboarding for initial app load

### ISSUE THREAD

**Issue by lukepereira** [serratus-bio/open-virome#51]
Currently users see a warning message to add filters and some rough summary statistics which don't work well for some of the original plots, e.g. displaying networks of the entire database.

Rayan suggested starting with an initial query which would solve this problem but would be annoying to clear every time . 

Some options:

- Auto-add example everytime and make it easier to clear all filters

- Add a optional click action to the warning message to load an example if the user wants. i.e. "Dataset is too large. [Add filters] in the query builder or [load an example]."

- Use local storage to only auto-add a query for first time users, otherwise don't add the example

**Comment by ababaian** [comment]
I think an initial query is the correct move, and the addition of a `Clear Query` button which removes all filters quickly.

For the auto-add example, I've been using `Eimeria` species, this makes sense as it pertains directly to what the virome documentatoin has been written to describe: i.e. https://github.com/serratus-bio/open-virome/wiki/Virome

This solves many issues with loading and data-points in complex queries. Also it shows people "interesting" data upfront.

**Comment by lukepereira** [comment]
When clearing query, we would have the same issues with our summary statistics views. Instead we probably want a welcome/landing screen.

The landing screen can include a logo, an action to open the filters, and the buttons to auto add example queries. Can be similar to this:
![Image](https://github.com/user-attachments/assets/407e3c61-317f-4b70-9256-ab70b3e1a70b)

**Comment by lukepereira** [comment]
The biome example I added is a placeholder since some updates need to be made to support biome filters.

We can update the examples as we explore biological use cases in the paper
