### ISSUE TITLE
sOTU based queries return all sOTU in "match" bioProjects

### ISSUE THREAD

**Issue by ababaian** [serratus-bio/open-virome#58]
![image](https://github.com/user-attachments/assets/07adcd0b-c019-421c-b020-b3a8fb246bee)

I have a query here for sOTU `u145189` and `u183036` with the purpose of retrieving the following component I have in R

![image](https://github.com/user-attachments/assets/b3e66c6b-a96e-479f-8131-0291a5d05cf1)

The current Open Virome returns a more complex network
![image](https://github.com/user-attachments/assets/d6b3da55-29fc-471d-82c4-a2a835fd7d92)

What appears to be happening is that all `runs` which have those sOTU are being matched (correctly), and then what the Virome Module is displaying is **all** sOTU in the matching runs, including those not specificed in the query are being displayed.

I think both behaviours are/can be technically correct, but the expected behaviour upfront I think should be to return/display **only** matching sOTU. Otherwise it's unclear why co-associated sOTU are being shown. This certainly will be neccesary when moving towards palm-palm networks to avoid pulling down huge clusters of unrelated sequences when querying by sOTU/Sequence.

**Comment by lukepereira** [comment]
I noticed this as well. I think there is more complexity when the user mixes multiple filters and the runs overlap, but it should be possible to filter out irrelevant sOTUs based on sOTU filters as a post-processing step

**Comment by ababaian** [comment]
> Ingrida
>  but maybe the issue is i am getting more than needed; or this is also as expected?
> See at the top: Virus Family: Polycipiviridae
> while in the graph: you have many different +ssRNA viruses, not just picorna-like
 
![image](https://github.com/user-attachments/assets/d4ab056d-d7d8-4c3d-a71e-68115cb2f816)

**Comment by ababaian** [comment]
Please add a `Time Estimate:` for this issue.

**Comment by ababaian** [comment]
For the above query; I'm now seeing two sOTU merged into one 🤔 

![Image](https://github.com/user-attachments/assets/6768a780-0b94-4398-89cd-66ad5be470e4)

**Comment by ababaian** [comment]
This could be related to the `tax_species` values being the same for these sOTU, they both have the same "top hit" in GenBank ![Image](https://github.com/user-attachments/assets/f67f76b4-2ce4-4b36-8051-8f4bef7f8e01)

**Comment by ababaian** [comment]
It looks like this is un-expected behavious due to `Virus Species` being used to group nodes; This doesn't match the [Virome mode](https://github.com/serratus-bio/open-virome/wiki/Virome) and should be sun-set for now. Could you make the default view `sOTU` and we can consider this issue closed and complete then.

**Comment by lukepereira** [comment]
Sounds good, I just set `sOTU` as the default option.

I still think it's useful to keep top genbank species as a label option, but we can discuss it in a separate issue.

**Comment by ababaian** [comment]
That's fair, can you make that label `GenBank Tophit` to be explicit?

**Comment by lukepereira** [comment]
Sure. We should open issues for unrelated new tasks

**Comment by lukepereira** [comment]
Pushed a change to rename it.

Closing this since the original issue is done, can open another issue if there's other follow ups to the labelling
