### ISSUE TITLE
Switch Domain from Amplify to `OpenVirome.com`

### ISSUE THREAD

**Issue by ababaian** [serratus-bio/open-virome#64]
In the AWS account Route 53 we own the `openvirome.com` domain, can we switch the URL so it looks nicer when sharing? Relatively high priority? @lukepereira

**Comment by lukepereira** [comment]
Can you check your Squarespace account and remove any redirects to `https//serratus.io/`. The rule doesn't seem to exist in AWS route53 so i'm assuming it was likely added in squarespace

**Comment by lukepereira** [comment]
the issue with the redirect was from the name server caching the old rule, which cleared for me after decreasing TTL.

I also needed to create a new certificate since we couldn't re-use *serratus.io, but it seems to be working for me https://openvirome.com/
