### ISSUE TITLE
Only include runs with palmprints in DB queries

### ISSUE THREAD

**Issue by lukepereira** [serratus-bio/open-virome#78]
Currently the app fetches all data even if there are no viruses in a given run. If we want the app to be focused on characterizing viruses, we can exclude a good chunk of runs which would make the app faster overall. 

The downside is that it may be useful  to display non-viral run metadata in the target vs. background set plots for certain queries.

If we decide to do this, the most performant approach would be to add a boolean column and index for `palm_virome` to `sra`. This was already done for the geo table.

- [x] Implement and push to prod for review
- [x] Add documentation on table dependencies

**Comment by ababaian** [comment]
This is worth implementing I would say, it will certainly boost performance. Is this stored as an `index` or is it a separate column added to the table?

**Comment by lukepereira** [comment]
Previously, Alex implemented by adding an extra column to the geo table. 

We can test whether joining on the `palm_virome` index is fast enough, otherwise we can add an extra column to sra table.

**Comment by ababaian** [comment]
- Implement as a separate `materialized view`, such that the original `sraruninfo` table (from NCBI source) is not modified.

**Comment by ababaian** [comment]
- As sub-task; document the dependencies of the `Query Builder` module.

**Comment by lukepereira** [comment]
@ababaian FYI

This is pushed to production for review. I implemented it so that [a configuration value](https://github.com/serratus-bio/open-virome/blob/8a1f71106cd2373cb421f37e76a138767c23a3e2/api/utils/queryBuilder.mjs#L1) can be changed to decide whether to exclude non-viral SRA runs. It's possible we make this a toggle on the front-end if we want to support both behaviours.

The virome and geo behaviour should be the same since they were already excluding non-viral sequences.

There are some behaviour changes to the features related to Run and Host modules:
- Counts are different on filters, which is expected
- Background vs. target plots have slightly different behaviour


Before:

Target set includes all runs that match filters, Background set is all runs in bioproject associated to matches

![Image](https://github.com/user-attachments/assets/093010ec-323d-4117-af03-845739f52469)


After:

Target set includes all runs that match filters **and have a virus**. Background set is all runs in bioproject (**including non-viral runs**) associated to matches

![Image](https://github.com/user-attachments/assets/f769898f-8835-403e-8014-c2d689ccb953)

I kind of like the change in behaviour since it provides a useful signal about the viruses, but we may need to reword things on UI. It's also possible to exclude viral runs in the background set.

**Comment by lukepereira** [comment]
Initial docs here: https://github.com/serratus-bio/open-virome/wiki/Query-Builder

Will continue to add/improve on the wiki this sprint

**Comment by ababaian** [comment]
:+1:  I think this is a great improvement, we will need to wordsmith what we're presenting and it's expected behaviour depending on the application, but this should be a good performance boost.
