### ISSUE TITLE
Geocoding on biosample attributes could be improved

### ISSUE THREAD

**Issue by almosnow** [serratus-bio/open-virome#86]
I was looking at several data points on the geo map and some of them are geocoded (text -> latlon) improperly.

It's not material but geocoding them with Google APIs yields much better results.

We had chose to use Amazon Location for this but I do see an improvement on switching to Google.

(Is there a way to use both and choose the best one?)

Leaving this here for future discussion.

**Comment by almosnow** [comment]
@ababaian Y/N?

**Comment by ababaian** [comment]
I'm leaning to no. The rate or measurement of improvement is undetermined, nor is there a measurement or benchmark to support this? 

Any method is flawed and unless there's a good rationale and method to validate strings for this, it's a "nice to have" feature which is non-essential.
