### ISSUE TITLE
bug: 500 error on dcoian99debdl.cloudfront.net

### ISSUE THREAD

**Issue by almosnow** [serratus-bio/open-virome#90]
One specific map query returns a 500 error

```
SELECT accession, attribute_name, attribute_value, ST_Y(lat_lon) as lat, ST_X(lat_lon) as lon, id
    FROM bgl_gp4326_wwf_tew_pv            
    LIMIT 65536;
```

I'm figuring it out what's happening

Update: It's not a cloudfront or lambda f. error but it's being thrown from the DB, not happening when using pgAdmin

**Comment by ababaian** [comment]
Is there a sticking point where this query is needed or is it a one-off error? Perhaps we can say: 
- Investigate bug for 2 hours
- If fix is not identified mark as `Not solved` and `triage` the issue

**Comment by almosnow** [comment]
Fixed.
