### ISSUE TITLE
API change on logan_AWS_RDS_proxy function to account for errors

### ISSUE THREAD

**Issue by almosnow** [serratus-bio/open-virome#91]
The function will be slightly refactored to _always_ return an object,

Either:

```
{ error:"..." }
```
or
```
{ result:"..." }
```

which are self explanatory, the reason for this is because it's easier to debug stuff on the client that through the intricate machine that is AWS.

I will adapt frontend/backend code for this.

**Comment by ababaian** [comment]
What has to be adapted for this? What's the timeline for implementation?

**Comment by ababaian** [comment]
Closed, triage.
