### ISSUE TITLE
[map] prune regions of high point density

### ISSUE THREAD

**Issue by almosnow** [serratus-bio/open-virome#94]
Many BioSamples resolve to the same geo location through multiple attributes (ex. explciit coordinates, but also city name, also country and it's the capital, ...)

"Pruning" them will improve rendering speed and quality, while keeping the information represented intact.

**Comment by ababaian** [comment]
Please improve documentation of this issue with more of the discussion we had in person.

**Comment by ababaian** [comment]
Please add a `Time Estimate:` for this issue.

**Comment by almosnow** [comment]
Time estimate 8 hours (2 half-days).

**Comment by almosnow** [comment]
Progress:

* Removed all labels related to institution or other names that are not directly related to a sample's location

**Comment by ababaian** [comment]
How was this done? What's the implementation?
