### ISSUE TITLE
[Analysis] Measure network homophily for metadata labels

### ISSUE THREAD

**Issue by lukepereira** [serratus-bio/open-virome#99]
### Overview

Many of our past experiments were implicitly relying on the phylogenetic network having strong [homophily](https://en.wikipedia.org/wiki/Network_homophily) in order to infer sOTU-Metadata label association.

By directly measuring homophily of different metadata labels on the phylogenetic network, we will be better positioned for modelling an optimal solution.

### Background / Context

See doc for more info: https://github.com/serratus-bio/open-virome/wiki/Metadata-imputation-with-network-topology

### Hypothesis

There is homophily of metadata features in the [phylogenetic network](https://github.com/serratus-bio/open-virome/wiki/Phylogenetic-Network).

### Experiment

1. Feature encode metadata labels 
2. Measure homophily of labels (edge homophily, node homophily, class insensitive edge homophily)
3. Repeat using different metadata labels and subgraphs 
    -  Metadata labels: tissue, organism, stat host, virus taxa, biome
    -  Graphs: full graph, organism subgraph, virus taxa subgraph, etc.

### Controls

Positive control: We expect to see high homophily when measuring the phylogenetic network using taxonomic labels.

Negative control: We expect to see low homophily when measuring the phylogenetic network using randomized labels.

### Expected Outcome

Based on past experiments, I expect that the overall graph homophily will be low (i.e. strong heterophily) but subgraphs of specific organisms will have higher homophily. 

This would explain why previous simple prediction models performed well on subsets of the data but did not generalize.

### Open Questions

Certain graph neural neworks can handle heterophily so long as the node degrees are high and the distributions of relationships are distinct between labels.

This opens the question of modelling or phylogenetic in a way to better take advantage of this property, i.e. using a tree structure

### References

https://github.com/serratus-bio/open-virome/wiki/Metadata-imputation-with-network-topology
https://arxiv.org/pdf/2111.12128
https://openreview.net/pdf?id=ucASPPD9GKN
https://pytorch-geometric.readthedocs.io/en/2.3.0/modules/utils.html#torch_geometric.utils.homophily

**Comment by lukepereira** [comment]
Progress on this can be viewed in recent lab meeting slides: https://docs.google.com/presentation/d/1TVmNinBXStvDynGogaRTeloSq-u_xDB18OULd_Y0_so/edit?usp=sharing

I was able to measure the basic edge homophily using single label per sOTU and saw the control case (taxa label) and most tissue label behave as expected.

<img width="855" alt="Screen Shot 2024-09-07 at 3 25 25 PM" src="https://github.com/user-attachments/assets/2fd1b31a-ca69-4594-935d-429f867e86fa">

<img width="854" alt="Screen Shot 2024-09-07 at 3 24 55 PM" src="https://github.com/user-attachments/assets/79463a62-9c31-468f-b60d-93354bb9a9e4">

I was able to measure multi-class homophily but was running into memory issues so had to use coarser features (hierarchy level 2) which created classes that made homophily measures less reliable.  I also made a first pass at setting up and running feature propagation on tissue labels to get a rought estimate of imputation power.

Follow ups:
- [x] Set up notebook on GPU cluster and re-do multi-class homophily on all feature hierarchy levels
- [x] Run USEARCH using lower threshold than 40%, review if disconnected sOTU problem is resolved
- [ ] Spend more time improving tissue/taxon labels by tuning [Louvain parameters](https://neo4j.com/docs/graph-data-science/current/algorithms/louvain/#algorithms-louvain-syntax).
- [ ] Open separate issue for feature propagation, evaluate using control of taxon labels. Evaluate by using features for simple classification task (before/after imputing features).

**Comment by ababaian** [comment]
> Run USEARCH using lower threshold than 40%, review if disconnected sOTU problem is resolved

This is a general descriptive statistic which we are lacking, if you vary threshold by increments of -5%, how does component number / edge number grow from 100% identity to 20% identity. The current implementation of `palm_graph` table uses a threshold of 30% identity which is quite close to what the theoretical limit is for sequence alignment (20%). You wouldn't have to re-calculate, but it would be worth making this plot for different graph statistics about edge connectivity so that we understand the shape of the data.

**Comment by lukepereira** [comment]
Agreed, i think this would be the most informative next step

**Comment by lukepereira** [comment]
Although decreasing p_ident threshold from 40% to 30% reduces the number of disconnected sOTUs from `378627`(74%)  to `366527` (71%) , it would increase number of edges from `26,341,751` to `630,180,732`.

Overall, we'll need a better strategy for imputing metadata on disconnected sOTUs in the phylogenetic network. Some options:
1. Add [metapaths](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.transforms.AddMetaPaths.html) to phylogenetic network (using common ancestor in NCBI taxonomy or common domains in pangenome)
2. Replace sequence similarity edges with structural similarity edges 
3. Replace sequence similarity edges with phylogenetic tree 
4. Use message-passing imputation on connected sOTUs, then use [MICE feature imputation](https://cran.r-project.org/web/packages/miceRanger/vignettes/miceAlgorithm.html) (network-free) on remaining disconnected sOTUs.


If we focus on creating a recommendation system for similar viromes (or bioprojects), I think leaving the disconnected sOTUs as is or trying approach 4 would be sufficient to get initial results. IMO we should work backwards from a recommendation system task and use it to evaluate how much adding imputed metadata improves performance. I can add a task for this to our backlog to clarify details.

![Image](https://github.com/user-attachments/assets/83fbbb88-a560-4014-aa16-756df1bd41b8)
![Image](https://github.com/user-attachments/assets/80ebb382-e17b-40e2-add1-368519a7a977)

**Comment by ababaian** [comment]
Why is the # of disconnected sOTU dropping with higher identity? Wouldn't a lower id threshold mean more connections?

**Comment by lukepereira** [comment]
Will fix in a sec, it's plotting something like cumulative difference when starting from 30%. I can plot the direct count at each interval instead since it'll be clearer

**Comment by lukepereira** [comment]
Decrease in disconnected sOTUs seems to flatten at 40%

<img width="875" alt="Screen Shot 2024-09-25 at 2 36 21 PM" src="https://github.com/user-attachments/assets/071fef7a-d7e3-4507-ab7a-34400a17287d">

**Comment by ababaian** [comment]
Can you post ~20 examples of disconnecred sOTU?

**Comment by lukepereira** [comment]
[isolated-sotus-20.txt](https://github.com/user-attachments/files/17157097/isolated-sotus-20.txt)
[isolated-sotus-200.txt](https://github.com/user-attachments/files/17157098/isolated-sotus-200.txt)

**Comment by lukepereira** [comment]
Investigation into isolated sOTUS will be tracked here: https://github.com/serratus-bio/open-virome/issues/125
